In [4]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (2.4.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 1.1 MB/s  0:00:021.0 MB/s eta 0:00:01:010m
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix
df=pd.read_csv('telco.csv')
df

      customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0     7590-VHVEG  Female              0  ...          29.85        29.85     No
1     5575-GNVDE    Male              0  ...          56.95       1889.5     No
2     3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3     7795-CFOCW    Male              0  ...          42.30      1840.75     No
4     9237-HQITU  Female              0  ...          70.70       151.65    Yes
...          ...     ...            ...  ...            ...          ...    ...
7038  6840-RESVB    Male              0  ...          84.80       1990.5     No
7039  2234-XADUH  Female              0  ...         103.20       7362.9     No
7040  4801-JZAZL  Female              0  ...          29.60       346.45     No
7041  8361-LTMKD    Male              1  ...          74.40        306.6    Yes
7042  3186-AJIEK    Male              0  ...         105.65       6844.5     No

[7043 rows x 21 columns]

In [3]:
X=df.drop(['customerID','Churn'],axis=1)
y = df['Churn'].map({'Yes': 1, 'No': 0})

In [4]:
X

      gender  SeniorCitizen  ... MonthlyCharges TotalCharges
0     Female              0  ...          29.85        29.85
1       Male              0  ...          56.95       1889.5
2       Male              0  ...          53.85       108.15
3       Male              0  ...          42.30      1840.75
4     Female              0  ...          70.70       151.65
...      ...            ...  ...            ...          ...
7038    Male              0  ...          84.80       1990.5
7039  Female              0  ...         103.20       7362.9
7040  Female              0  ...          29.60       346.45
7041    Male              1  ...          74.40        306.6
7042    Male              0  ...         105.65       6844.5

[7043 rows x 19 columns]

In [5]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [29]:
def engineer_features(df):
    X=df.copy()
    X['charge_per_tenure'] = X['MonthlyCharges'] / (X['tenure'] + 1)
    service_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
                    'TechSupport', 'StreamingTV', 'StreamingMovies']
    # Convert 'Yes' to 1, others to 0
    X['service_count'] = (X[service_cols] == 'Yes').sum(axis=1)
    X['is_automatic_payment'] = X['PaymentMethod'].str.contains('automatic').astype(int)
    
    return X

In [30]:
X.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
dtype: int64

In [31]:
num_cols=['SeniorCitizen', 'tenure', 'MonthlyCharges','charge_per_tenure','is_automatic_payment']
cat_cols = ['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'PhoneService', 
                        'MultipleLines', 'InternetService', 'OnlineSecurity', 'Contract', 
                        'PaymentMethod', 'is_automatic_payment']

In [32]:
num_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

cat_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer([
    ('num', num_transformer, num_cols),
    ('cat', cat_transformer, cat_cols)
])


full_pipeline = Pipeline([
    ('feature_eng', FunctionTransformer(engineer_features)),
    ('preprocessor', preprocessor),
    ('classifier', xgb.XGBClassifier(
        eval_metric='logloss',
        scale_pos_weight=3,  # Handles class imbalance for better Recall
        random_state=42
    ))
])

In [34]:
param_grid = {
    'classifier__max_depth': [3, 5],
    'classifier__learning_rate': [0.01, 0.1],
    'classifier__n_estimators': [100, 200],
    'classifier__subsample': [0.8, 1.0]
}


grid_search = GridSearchCV(
    full_pipeline, 
    param_grid, 
    cv=5, 
    scoring='f1', # Targeting your specific KPI
    n_jobs=-1,
    verbose=1
)


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
grid_search.fit(X_train, y_train)

print(f"Best Params: {grid_search.best_params_}")

y_probs = grid_search.predict_proba(X_test)[:, 1]
y_pred_tight = (y_probs > 0.65).astype(int) 

print(classification_report(y_test, y_pred_tight))
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best Params: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 3, 'classifier__n_estimators': 200, 'classifier__subsample': 1.0}
              precision    recall  f1-score   support

           0       0.87      0.82      0.85      1035
           1       0.57      0.66      0.61       374

    accuracy                           0.78      1409
   macro avg       0.72      0.74      0.73      1409
weighted avg       0.79      0.78      0.78      1409

              precision    recall  f1-score   support

           0       0.92      0.71      0.80      1035
           1       0.51      0.82      0.63       374

    accuracy                           0.74      1409
   macro avg       0.71      0.77      0.71      1409
weighted avg       0.81      0.74      0.76      1409